# Generated by Django 3.2.5 on 2021-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variationmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
